### ISSUE TITLE
Xboard mode Invalid Moves

### ISSUE THREAD

**Issue by brianprichardson** [Mk-Chan/WyldChess#41]
When running as Xboard under Winboard with an EPD file of starting positions, there are many games forfeited with invalid move errors.  No problems so far as UCI under Winboard and same EPD file.

**Comment by Mk-Chan** [comment]
That's interesting... I tried (this book)[https://github.com/ianfab/books/blob/master/chess.epd] and it seems to work perfectly fine under cutechess but indeed produces invalid move errors under Xboard.

I'll try to look into it, thanks for informing me. Until then I guess UCI is ok.

**Comment by Mk-Chan** [comment]
I believe I managed to fix it, it was apparently due to me setting the side to move based on the `setboard`command. It'll be included in the next release.
