### ISSUE TITLE
General asking - incl. "make" problem

### ISSUE THREAD

**Issue by LocutusOfPenguin** [Mk-Chan/WyldChess#44]
Hi,
im using Ubuntu, and when i try to compile wyldChess, it complains about win$dows build problems.
Its working, but these error messages should be avoided.

Can y change the make file so to allow unix compile only?

Next: for the "picochess" project...im always looking for alternative engines.
Can y comment if the following is in the "pipeline", and if yes, when it can be seen?

- uci960 support
- levels support or even better elo-settings

see stockfish for a working example
Jürgen

**Comment by Mk-Chan** [comment]
Hi Juergen,
    I think you must have compiled using the `build.sh` script. That actually tries to compile the entire release including the Windows stuff. I should put in a check for the windows compile you're right.
    Normally you'd want to compile going into the src folder and do either `make bmi`, `make popcnt` or `make` depending on the requirement. But anyway, I'll update the `build.sh` script since it really should have more checks.
    Chess960 support is planned and I will probably get to it after a few things. Elo-setting/level support is not planned for anywhere in the near future.

**Comment by LocutusOfPenguin** [comment]
Thanks for the quick answer.
Yes, i used "build.sh"

That's great to hear y go for uci960! If that's ready before i'm ready for v1.0 there is a chance it goes to the DGT-Pi clock :-)
For levels, well...we all need to get stronger to have a chance against such programs even on a RaspPi.

Jürgen

**Comment by Mk-Chan** [comment]
The thing with levels is that I can implement something very approximate with not too much difficulty but to do it properly will need testing strength at multiple elo-strengths(2000,2100,2200..2700) will be hard I think may need lots of time/resources. But I'll give that a try too

**Comment by LocutusOfPenguin** [comment]
yes, im fully aware that levels are alot harder as uci960 (just need to update yr castle gen).

If ELO ratings are exact is not said...It just looks nicer, and surely, it depends on the HW alot.
For us, its just harder to find weak programs then programs >2200. But the people using picochess are seldom in this area. I just throw "claudia" out...that was used in the (sold) dgtpi clock for the target group of weak players (buyers), ha.

Y could limit the nodes/sec for example..But im out of business for writing chess programs.
If thats too complex, its so...But i can ask :-) Thanks!

**Comment by Mk-Chan** [comment]
I can try some scheme(maybe limiting nodes/sec like you suggest) to set levels it's not that it's a problem but it will take time to do well. Chess960 I'll do once I'm done tweaking my Lazy SMP scheme.

**Comment by Mk-Chan** [comment]
Build system is better now with checks and a much cleaner script. Getting to work on Chess960 this week

**Comment by LocutusOfPenguin** [comment]
Great news   thx

**Comment by LocutusOfPenguin** [comment]
Hi,
i even have found more "issues" - and they are for me (as picochess dev) even more important as [uci960 &] "level" which is not easy to do right (we talked about it already). Its all about uci implementation - so not only important for me.

I apologize for always having more requests. I can offer my help - but i'm not that terrific good C-dev ;-)
Anyway, its always possible to ignore it - or move ahead in time.
Jürgen

**Comment by Mk-Chan** [comment]
I've been looking at chess960, I have thought of the way to implement it too, I'm just verifying that there are no loose ends and this shouldn't be too far off either.

Levels I can't precisely say for now, but it will take a longer time

**Comment by LocutusOfPenguin** [comment]
Thanks.
I saw already, that y still busy with yr our branch.
I mainly said this cause if y follow my wishes, the levels is not that important as #45 and "levels" also harder to implement.
