### ISSUE TITLE
WyldChess - binaries for Windows are missing

### ISSUE THREAD

**Issue by ChessGUI** [Mk-Chan/WyldChess#5]
Can you create Windows binaries 32/64 bit of your engine and host these files on GitHub, please?
Has your program any reletionship to Wyld UCI, a former derivative of Stockfish ?

OS: Microsoft 7 SP1 32 & 64 bit
Intel Core i5 3470 - 4 GB RAM
        Cores   4
        Threads 4
        Name    Intel Core i5 3470
        Code Name       Ivy Bridge
        Package Socket 1155 LGA
        Technology      22nm
        Specification   Intel Core i5-3470 CPU @ 3.20GHz
        Family  6
        Extended Family 6
        Model   A
        Extended Model  3A
        Stepping        9
        Revision        N0
        Instructions    MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX, VMX, AES, AVX
        Virtualization  Supported, Enabled
        Hyperthreading  Supported, Disabled

**Comment by Mk-Chan** [comment]
I do intend to make Windows binaries, I'm working on GNU/Linux so the program might take some tweaking but it shouldn't take too long.
And no, my engine is not related to any engine called Wyld UCI. I hadn't even heard of any other chess engine with this name

**Comment by Mk-Chan** [comment]
I have created and hosted the 32/64-bit Windows binaries, could you please verify that they work as intended and get back to me
